package pl.edu.pwr.student.djablonski.database.database;

import pl.edu.pwr.student.djablonski.database.exceptions.MigrationException;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public abstract class Migration {
    public static void migrate(Connection DB) throws MigrationException {
        try{
            Statement statement = DB.createStatement();

            //tables
            statement.execute("""
                            create table if not exists obywatel
                            (
                                id    integer not null
                                    constraint id
                                        primary key autoincrement,
                                nazwa text    not null
                            );
                            """);
            statement.execute("""
                            create table if not exists kontroler
                            (
                                id    integer not null
                                    constraint id
                                        primary key autoincrement,
                                nazwa text    not null
                            );
                            """);
            statement.execute("""
                            create table if not exists kierownik
                            (
                                id    integer not null
                                    constraint id
                                        primary key autoincrement,
                                nazwa text    not null
                            );
                            """);
            statement.execute("""
                            create table if not exists zgloszenie
                            (
                                id              integer not null
                                        constraint id
                                            primary key autoincrement,
                                    id_obywatela    integer not null
                                        constraint id
                                            references obywatel,
                                    status          text    not null,
                                    data_zgloszenia INTEGER not null,
                                    id_kontrolera   integer
                                        constraint id_kontrolera
                                            references kontroler
                            );
                            """);
            statement.execute("""
                            create table if not exists decyzja
                            (
                                id    integer not null
                                constraint id
                                primary key autoincrement,
                                id_zgloszenia integer not null
                                constraint id
                                references zgloszenie,
                                id_kierownika integer not null
                                constraint id
                                references kierownik,
                                opis          text
                            );
                            """);
            statement.execute("""
                            create table if not exists drzewo
                            (
                                id         integer not null
                                    constraint id
                                        primary key autoincrement,
                                nazwa         text,
                                srednica      integer not null,
                                id_zgloszenia integer not null
                                    constraint id
                                        references zgloszenie
                            );
                            """);
            statement.execute("""
                            create table if not exists raport
                            (
                                id    integer not null
                                    constraint id
                                        primary key autoincrement,
                                id_zgloszenia integer not null
                                    constraint id
                                        references zgloszenie,
                                opis          text
                            );
                            """);

        } catch (SQLException e){
            throw new MigrationException(e);
        }
    }
    public static void mocData(Connection DB) throws MigrationException {
        try{
            Statement statement = DB.createStatement();

            //data in tables
            statement.execute("""
                    insert into `kontroler` values
                            ( null,"Oliver"),
                            ( null,"Jackson"),
                            ( null,"William"),
                            ( null,"Benjamin"),
                            ( null,"Noah"),
                            ( null,"Liam"),
                            ( null,"Samuel"),
                            ( null,"Henry"),
                            ( null,"Michael"),
                            ( null,"Daniel")
                            """);
            statement.execute("""
                    insert into `kierownik` values
                            ( null,"Oliver"),
                            ( null,"Jackson"),
                            ( null,"William"),
                            ( null,"Benjamin"),
                            ( null,"Noah"),
                            ( null,"Liam"),
                            ( null,"Samuel"),
                            ( null,"Henry"),
                            ( null,"Michael"),
                            ( null,"Daniel")
                            """);
            statement.execute("""

                    insert into `obywatel` values
                            ( null,"Oliver"),
                            ( null,"Jackson"),
                            ( null,"William"),
                            ( null,"Benjamin"),
                            ( null,"Noah"),
                            ( null,"Liam"),
                            ( null,"Samuel"),
                            ( null,"Henry"),
                            ( null,"Michael"),
                            ( null,"Daniel"),
                            ( null,"James"),
                            ( null,"Mason"),
                            ( null,"Ethan"),
                            ( null,"Alexander"),
                            ( null,"Aiden"),
                            ( null,"Elijah"),
                            ( null,"Logan"),
                            ( null,"Jack"),
                            ( null,"Lucas"),
                            ( null,"Max"),
                            ( null,"Levi"),
                            ( null,"Owen"),
                            ( null,"Mateo"),
                            ( null,"Wyatt"),
                            ( null,"Carter"),
                            ( null,"Jaxon"),
                            ( null,"Leo"),
                            ( null,"Julian"),
                            ( null,"Ezra"),
                            ( null,"Caleb"),
                            ( null,"Grayson"),
                            ( null,"Colton"),
                            ( null,"Riley"),
                            ( null,"Cooper"),
                            ( null,"Hudson"),
                            ( null,"Brayden"),
                            ( null,"Jasper"),
                            ( null,"Jayden"),
                            ( null,"Declan"),
                            ( null,"Adrian"),
                            ( null,"Zane"),
                            ( null,"Tristan"),
                            ( null,"Miles"),
                            ( null,"Isaiah"),
                            ( null,"Ryker"),
                            ( null,"Eli"),
                            ( null,"Finn"),
                            ( null,"Lincoln"),
                            ( null,"Asher"),
                            ( null,"Brody"),
                            ( null,"Ayden"),
                            ( null,"Camden"),
                            ( null,"Jaxon"),
                            ( null,"Kaiden"),
                            ( null,"Grayson"),
                            ( null,"Maverick"),
                            ( null,"Kyler"),
                            ( null,"Lorenzo"),
                            ( null,"Beau"),
                            ( null,"Emerson"),
                            ( null,"Jayce"),
                            ( null,"Boden"),
                            ( null,"Callan"),
                            ( null,"Colt"),
                            ( null,"Daxton"),
                            ( null,"Declan"),
                            ( null,"Dominic"),
                            ( null,"Emmett"),
                            ( null,"Enzo"),
                            ( null,"Everett"),
                            ( null,"Felix"),
                            ( null,"Finley"),
                            ( null,"Gage"),
                            ( null,"Greyson"),
                            ( null,"Gunnar"),
                            ( null,"Hayden"),
                            ( null,"Hayes"),
                            ( null,"Jaxon"),
                            ( null,"Jenson"),
                            ( null,"Jesse"),
                            ( null,"John"),
                            ( null,"Jonas"),
                            ( null,"Kai"),
                            ( null,"Kamden"),
                            ( null,"Kane"),
                            ( null,"Karson"),
                            ( null,"Kayden"),
                            ( null,"Keegan"),
                            ( null,"Keenan"),
                            ( null,"Kennedy"),
                            ( null,"Kian"),
                            ( null,"Kingston"),
                            ( null,"Knox"),
                            ( null,"Kolton"),
                            ( null,"Kyson"),
                            ( null,"Landon"),
                            ( null,"Landry"),
                            ( null,"Lane"),
                            ( null,"Lawson"),
                            ( null,"Leighton"),
                            ( null,"Levi"),
                            ( null,"Liam"),
                            ( null,"Lincoln"),
                            ( null,"Logan"),
                            ( null,"Luke"),
                            ( null,"Maddox"),
                            ( null,"Malachi"),
                            ( null,"Mason"),
                            ( null,"Maverick"),
                            ( null,"Max"),
                            ( null,"Micah"),
                            ( null,"Miles"),
                            ( null,"Mitchell"),
                            ( null,"Nash"),
                            ( null,"Navarro"),
                            ( null,"Nehemiah"),
                            ( null,"Nicholas"),
                            ( null,"Nolan"),
                            ( null,"Oliver"),
                            ( null,"Omar"),
                            ( null,"Parker"),
                            ( null,"Patrick"),
                            ( null,"Paul"),
                            ( null,"Paxton"),
                            ( null,"Peyton"),
                            ( null,"Phoenix"),
                            ( null,"Porter"),
                            ( null,"Quinn"),
                            ( null,"Ramon"),
                            ( null,"Reed"),
                            ( null,"Remington"),
                            ( null,"Rhett"),
                            ( null,"River"),
                            ( null,"Roan"),
                            ( null,"Robert"),
                            ( null,"Roman"),
                            ( null,"Ryder"),
                            ( null,"Ryker"),
                            ( null,"Sage"),
                            ( null,"Samuel"),
                            ( null,"Santiago"),
                            ( null,"Sawyer"),
                            ( null,"Sebastian"),
                            ( null,"Silas"),
                            ( null,"Theodore"),
                            ( null,"Thomas"),
                            ( null,"Tristan"),
                            ( null,"Tucker"),
                            ( null,"Tyler"),
                            ( null,"Walker"),
                            ( null,"William"),
                            ( null,"Wyatt"),
                            ( null,"Xander"),
                            ( null,"Zane"),
                            ( null,"Eleanor"),
                            ( null,"Olivia"),
                            ( null,"Emma"),
                            ( null,"Ava"),
                            ( null,"Sophia"),
                            ( null,"Isabella"),
                            ( null,"Charlotte"),
                            ( null,"Mia"),
                            ( null,"Amelia"),
                            ( null,"Harper"),
                            ( null,"Evelyn"),
                            ( null,"Avery"),
                            ( null,"Sofia"),
                            ( null,"Cleo"),
                            ( null,"Eliana"),
                            ( null,"Abigail"),
                            ( null,"Nora"),
                            ( null,"Gracie"),
                            ( null,"Mila"),
                            ( null,"Addison"),
                            ( null,"Ellie"),
                            ( null,"Violet"),
                            ( null,"Aubrey"),
                            ( null,"Lily"),
                            ( null,"Lucy"),
                            ( null,"Layla"),
                            ( null,"Emma"),
                            ( null,"Madelyn"),
                            ( null,"Savannah"),
                            ( null,"Chole"),
                            ( null,"Paisley"),
                            ( null,"Serenity"),
                            ( null,"Nova"),
                            ( null,"Addison"),
                            ( null,"Natalie"),
                            ( null,"Liliana"),
                            ( null,"Brooklyn"),
                            ( null,"Aubrey"),
                            ( null,"Claire"),
                            ( null,"Ryleigh"),
                            ( null,"Kennedy"),
                            ( null,"Skylar"),
                            ( null,"Dream"),
                            ( null,"Amara"),
                            ( null,"Aaliyah"),
                            ( null,"Jocelyn"),
                            ( null,"Leilani"),
                            ( null,"Makayla"),
                            ( null,"Ember"),
                            ( null,"Ensley"),
                            ( null,"Jordyn"),
                            ( null,"Adalynn"),
                            ( null,"Vera"),
                            ( null,"Emerson"),
                            ( null,"Sutton"),
                            ( null,"Hailey"),
                            ( null,"Everly"),
                            ( null,"Remi"),
                            ( null,"Lyla"),
                            ( null,"Lena"),
                            ( null,"Malia"),
                            ( null,"Presley"),
                            ( null,"Madelyn"),
                            ( null,"Ruby"),
                            ( null,"Ainsley"),
                            ( null,"Jane"),
                            ( null,"Alice"),
                            ( null,"Sadie"),
                            ( null,"Iris"),
                            ( null,"Paisley"),
                            ( null,"Melanie"),
                            ( null,"Theadora"),
                            ( null,"Eloise"),
                            ( null,"Arielle"),
                            ( null,"Vivian"),
                            ( null,"Remy"),
                            ( null,"Lucy"),
                            ( null,"Wren"),
                            ( null,"Kyla"),
                            ( null,"Brielle"),
                            ( null,"Marley"),
                            ( null,"Blair"),
                            ( null,"Sawyer"),
                            ( null,"Rylie"),
                            ( null,"Remington"),
                            ( null,"Lennox"),
                            ( null,"Ryann"),
                            ( null,"Amari"),
                            ( null,"Coralie"),
                            ( null,"Journey"),
                            ( null,"Rylan"),
                            ( null,"Collins"),
                            ( null,"Alayah"),
                            ( null,"Waverly"),
                            ( null,"Leighton"),
                            ( null,"Stokely"),
                            ( null,"Haven"),
                            ( null,"Winter"),
                            ( null,"Wren"),
                            ( null,"Monroe"),
                            ( null,"Zuri"),
                            ( null,"Everly"),
                            ( null,"Kairi"),
                            ( null,"Lyla"),
                            ( null,"Rowan"),
                            ( null,"Aaliyah"),
                            ( null,"Liliana"),
                            ( null,"Kensley"),
                            ( null,"Emberly"),
                            ( null,"Maeve"),
                            ( null,"Elena"),
                            ( null,"Hadley"),
                            ( null,"Wren"),
                            ( null,"Aubrey"),
                            ( null,"Campbell"),
                            ( null,"Paisley"),
                            ( null,"Sutton"),
                            ( null,"Ryleigh"),
                            ( null,"Brynlee"),
                            ( null,"Eliana"),
                            ( null,"Kinsley"),
                            ( null,"Leighton"),
                            ( null,"Waverly"),
                            ( null,"Aaliyah"),
                            ( null,"Avery"),
                            ( null,"Journey"),
                            ( null,"Liliana"),
                            ( null,"Paisley"),
                            ( null,"Sawyer"),
                            ( null,"Leila"),
                            ( null,"Brynlee"),
                            ( null,"Emberly"),
                            ( null,"Ainsley"),
                            ( null,"Brielle"),
                            ( null,"Kinsley"),
                            ( null,"Rylan"),
                            ( null,"Eliana"),
                            ( null,"Adalynn"),
                            ( null,"Leilani"),
                            ( null,"Rylee"),
                            ( null,"Amara"),
                            ( null,"Leighton"),
                            ( null,"Marley"),
                            ( null,"Winter"),
                            ( null,"Brielle"),
                            ( null,"Avery"),
                            ( null,"Ryann"),
                            ( null,"Rylan"),
                            ( null,"Collins"),
                            ( null,"Brynlee"),
                            ( null,"Monroe"),
                            ( null,"Aaliyah"),
                            ( null,"Ryann"),
                            ( null,"Ainsley"),
                            ( null,"Alayah"),
                            ( null,"Rowan"),
                            ( null,"Collins"),
                            ( null,"Rylan"),
                            ( null,"Collins"),
                            ( null,"Wren"),
                            ( null,"Ryleigh"),
                            ( null,"Brynlee"),
                            ( null,"Marley"),
                            ( null,"Kinsley"),
                            ( null,"Leila"),
                            ( null,"Remy")
                            """);

            statement.execute("""
                    insert into `zgloszenie` values
                        (null,1,"zlozone",1700000020,null),
                        (null,2,"zlozone",1700000021,null),
                        (null,3,"zlozone",1700000022,null),
                        (null,4,"zlozone",1700000023,null),
                        (null,5,"zlozone",1700000024,null),
                        (null,6,"zlozone",1700000025,null),
                        (null,7,"zlozone",1700000026,null),
                        (null,8,"zlozone",1700000027,null),
                        (null,9,"zlozone",1700000028,null),
                        (null,10,"zlozone",1700000029,null),
                        (null,11,"zlozone",1700000030,null),
                        (null,12,"zlozone",1700000031,null),
                        (null,13,"zlozone",1700000032,null),
                        (null,14,"zlozone",1700000033,null),
                        (null,15,"zlozone",1700000034,null),
                        (null,16,"zlozone",1700000035,null),
                        (null,17,"zlozone",1700000036,null),
                        (null,18,"zlozone",1700000037,null),
                        (null,19,"zlozone",1700000038,null),
                        (null,20,"zlozone",1700000039,null),
                        (null,21,"zlozone",1700000040,null),
                        (null,22,"zlozone",1700000041,null),
                        (null,23,"zlozone",1700000042,null),
                        (null,24,"zlozone",1700000043,null),
                        (null,25,"zlozone",1700000044,null),
                        (null,26,"zlozone",1700000045,null),
                        (null,27,"zlozone",1700000046,null),
                        (null,28,"zlozone",1700000047,null),
                        (null,29,"zlozone",1700000048,null),
                        (null,30,"zlozone",1700000049,null),
                        (null,31,"zlozone",1700000050,null),
                        (null,32,"zlozone",1700000051,null),
                        (null,33,"zlozone",1700000052,null),
                        (null,34,"zlozone",1700000053,null),
                        (null,35,"zlozone",1700000054,null),
                        (null,36,"zlozone",1700000055,null),
                        (null,37,"zlozone",1700000056,null),
                        (null,38,"zlozone",1700000057,null),
                        (null,39,"zlozone",1700000058,null),
                        (null,40,"zlozone",1700000059,null),
                        (null,41,"zlozone",1700000060,null),
                        (null,42,"zlozone",1700000061,null),
                        (null,44,"zlozone",1700000063,null),
                        (null,45,"zlozone",1700000064,null),
                        (null,46,"zlozone",1700000065,null),
                        (null,47,"zlozone",1700000066,null),
                        (null,48,"zlozone",1700000067,null),
                        (null,49,"zlozone",1700000068,null),
                        (null,50,"zlozone",1700000069,null),
                        (null,51,"zlozone",1700000070,null),
                        (null,52,"zlozone",1700000071,null),
                        (null,53,"zlozone",1700000072,null),
                        (null,54,"zlozone",1700000073,null),
                        (null,55,"zlozone",1700000074,null),
                        (null,56,"zlozone",1700000075,null),
                        (null,57,"zlozone",1700000076,null),
                        (null,58,"zlozone",1700000077,null),
                        (null,59,"zlozone",1700000078,null),
                        (null,60,"zlozone",1700000079,null),
                        (null,61,"zlozone",1700000080,null),
                        (null,62,"zlozone",1700000081,null),
                        (null,63,"zlozone",1700000082,null),
                        (null,64,"zlozone",1700000083,null),
                        (null,65,"zlozone",1700000084,null),
                        (null,66,"zlozone",1700000085,null),
                        (null,67,"zlozone",1700000086,null),
                        (null,68,"zlozone",1700000087,null),
                        (null,69,"zlozone",1700000088,null),
                        (null,70,"zlozone",1700000089,null),
                        (null,71,"zlozone",1700000090,null),
                        (null,72,"zlozone",1700000091,null),
                        (null,73,"zlozone",1700000092,null),
                        (null,74,"zlozone",1700000093,null),
                        (null,75,"zlozone",1700000094,null),
                        (null,76,"zlozone",1700000095,null),
                        (null,77,"zlozone",1700000096,null),
                        (null,78,"zlozone",1700000097,null),
                        (null,79,"zlozone",1700000098,null),
                        (null,80,"zlozone",1700000099,null),
                        (null,81,"zlozone",1700000100,null),
                        (null,1,"zlozone",1700000020,null),
                        (null,2,"zlozone",1700000021,null),
                        (null,3,"zlozone",1700000022,null),
                        (null,4,"zlozone",1700000023,null),
                        (null,5,"zlozone",1700000024,null),
                        (null,6,"zlozone",1700000025,null),
                        (null,7,"zlozone",1700000026,null),
                        (null,8,"zlozone",1700000027,null),
                        (null,9,"zlozone",1700000028,null),
                        (null,10,"zlozone",1700000029,null),
                        (null,11,"zlozone",1700000030,null),
                        (null,12,"zlozone",1700000031,null),
                        (null,13,"zlozone",1700000032,null),
                        (null,14,"zlozone",1700000033,null),
                        (null,15,"zlozone",1700000034,null),
                        (null,16,"zlozone",1700000035,null),
                        (null,17,"zlozone",1700000036,null),
                        (null,18,"zlozone",1700000037,null),
                        (null,19,"zlozone",1700000038,null),
                        (null,20,"zlozone",1700000039,null),
                        (null,21,"zlozone",1700000040,null),
                        (null,22,"zlozone",1700000041,null),
                        (null,23,"zlozone",1700000042,null),
                        (null,24,"zlozone",1700000043,null),
                        (null,25,"zlozone",1700000044,null),
                        (null,26,"zlozone",1700000045,null),
                        (null,27,"zlozone",1700000046,null),
                        (null,28,"zlozone",1700000047,null),
                        (null,29,"zlozone",1700000048,null),
                        (null,30,"zlozone",1700000049,null),
                        (null,31,"zlozone",1700000050,null),
                        (null,32,"zlozone",1700000051,null),
                        (null,33,"zlozone",1700000052,null),
                        (null,34,"zlozone",1700000053,null),
                        (null,35,"zlozone",1700000054,null),
                        (null,36,"zlozone",1700000055,null),
                        (null,37,"zlozone",1700000056,null),
                        (null,38,"zlozone",1700000057,null),
                        (null,39,"zlozone",1700000058,null),
                        (null,40,"zlozone",1700000059,null),
                        (null,41,"zlozone",1700000060,null),
                        (null,42,"zlozone",1700000061,null),
                        (null,44,"zlozone",1700000063,null),
                        (null,45,"zlozone",1700000064,null),
                        (null,46,"zlozone",1700000065,null),
                        (null,47,"zlozone",1700000066,null),
                        (null,48,"zlozone",1700000067,null),
                        (null,49,"zlozone",1700000068,null),
                        (null,50,"zlozone",1700000069,null),
                        (null,51,"zlozone",1700000070,null),
                        (null,52,"zlozone",1700000071,null),
                        (null,53,"zlozone",1700000072,null),
                        (null,54,"zlozone",1700000073,null),
                        (null,55,"zlozone",1700000074,null),
                        (null,56,"zlozone",1700000075,null),
                        (null,57,"zlozone",1700000076,null),
                        (null,58,"zlozone",1700000077,null),
                        (null,59,"zlozone",1700000078,null),
                        (null,60,"zlozone",1700000079,null),
                        (null,61,"zlozone",1700000080,null),
                        (null,62,"zlozone",1700000081,null),
                        (null,63,"zlozone",1700000082,null),
                        (null,64,"zlozone",1700000083,null),
                        (null,65,"zlozone",1700000084,null),
                        (null,66,"zlozone",1700000085,null),
                        (null,67,"zlozone",1700000086,null),
                        (null,68,"zlozone",1700000087,null),
                        (null,69,"zlozone",1700000088,null),
                        (null,70,"zlozone",1700000089,null),
                        (null,71,"zlozone",1700000090,null),
                        (null,72,"zlozone",1700000091,null),
                        (null,73,"zlozone",1700000092,null),
                        (null,74,"zlozone",1700000093,null),
                        (null,75,"zlozone",1700000094,null),
                        (null,76,"zlozone",1700000095,null),
                        (null,77,"zlozone",1700000096,null),
                        (null,78,"zlozone",1700000097,null),
                        (null,79,"zlozone",1700000098,null),
                        (null,80,"zlozone",1700000099,null),
                        (null,44,"zlozone",1700000063,null),
                        (null,45,"zlozone",1700000064,null),
                        (null,46,"zlozone",1700000065,null),
                        (null,47,"zlozone",1700000066,null),
                        (null,48,"zlozone",1700000067,null),
                        (null,49,"zlozone",1700000068,null),
                        (null,50,"zlozone",1700000069,null),
                        (null,51,"zlozone",1700000070,null),
                        (null,52,"zlozone",1700000071,null),
                        (null,53,"zlozone",1700000072,null),
                        (null,54,"zlozone",1700000073,null),
                        (null,55,"zlozone",1700000074,null),
                        (null,56,"zlozone",1700000075,null),
                        (null,57,"zlozone",1700000076,null),
                        (null,58,"zlozone",1700000077,null),
                        (null,59,"zlozone",1700000078,null),
                        (null,60,"zlozone",1700000079,null),
                        (null,61,"zlozone",1700000080,null),
                        (null,62,"zlozone",1700000081,null),
                        (null,63,"zlozone",1700000082,null),
                        (null,64,"zlozone",1700000083,null),
                        (null,65,"zlozone",1700000084,null),
                        (null,66,"zlozone",1700000085,null),
                        (null,67,"zlozone",1700000086,null),
                        (null,68,"zlozone",1700000087,null),
                        (null,69,"zlozone",1700000088,null),
                        (null,70,"zlozone",1700000089,null),
                        (null,71,"zlozone",1700000090,null),
                        (null,72,"zlozone",1700000091,null),
                        (null,73,"zlozone",1700000092,null),
                        (null,74,"zlozone",1700000093,null),
                        (null,75,"zlozone",1700000094,null),
                        (null,76,"zlozone",1700000095,null),
                        (null,77,"zlozone",1700000096,null),
                        (null,78,"zlozone",1700000097,null),
                        (null,79,"zlozone",1700000098,null),
                        (null,80,"zlozone",1700000099,null);
            """);

            statement.execute("""
                insert into `drzewo` values
                         (null, 'oak', 150, 134),
                         (null, 'maple', 76, 117),
                         (null, 'pine', 141, 41),
                         (null, 'birch', 196, 126),
                         (null, 'elm', 100, 119),
                         (null, 'ash', 67, 104),
                         (null, 'beech', 112, 14),
                         (null, 'poplar', 188, 98),
                         (null, 'willow', 131, 93),
                         (null, 'cherry', 94, 26),
                         (null, 'oak', 56, 165),
                         (null, 'maple', 91, 76),
                         (null, 'pine', 64, 183),
                         (null, 'birch', 144, 118),
                         (null, 'elm', 128, 52),
                         (null, 'ash', 78, 194),
                         (null, 'beech', 156, 133),
                         (null, 'poplar', 118, 132),
                         (null, 'willow', 113, 101),
                         (null, 'cherry', 50, 105),
                         (null, 'oak', 181, 63),
                         (null, 'maple', 124, 134),
                         (null, 'pine', 83, 36),
                         (null, 'birch', 167, 142),
                         (null, 'elm', 52, 191),
                         (null, 'ash', 111, 38),
                         (null, 'beech', 84, 5),
                         (null, 'poplar', 65, 45),
                         (null, 'willow', 100, 161),
                         (null, 'cherry', 147, 143),
                         (null, 'oak', 137, 150),
                         (null, 'maple', 169, 178),
                         (null, 'pine', 172, 74),
                         (null, 'birch', 191, 17),
                         (null, 'elm', 69, 186),
                         (null, 'ash', 103, 158),
                         (null, 'beech', 139, 163),
                         (null, 'poplar', 107, 155),
                         (null, 'willow', 72, 124),
                         (null, 'cherry', 53, 138),
                         (null, 'oak', 62, 102),
                         (null, 'maple', 132, 149),
                         (null, 'pine', 198, 160),
                         (null, 'birch', 110, 131),
                         (null, 'elm', 109, 13),
                         (null, 'ash', 149, 27),
                         (null, 'beech', 177, 146),
                         (null, 'poplar', 88, 20),
                         (null, 'willow', 140, 42),
                         (null, 'cherry', 125, 167),
                         (null,'Oak',132,123),
                         (null,'Birch',111,184),
                         (null,'Pine',50,10),
                         (null,'Spruce',176,167),
                         (null,'Maple',145,193),
                         (null,'Ash',82,20),
                         (null,'Beech',100,152),
                         (null,'Elm',63,91),
                         (null,'Willow',121,11),
                         (null,'Poplar',196,12),
                         (null,'Aspen',75,45),
                         (null,'Hawthorn',154,196),
                         (null,'Dogwood',138,13),
                         (null,'Hazelnut',107,18),
                         (null,'Alder',162,15),
                         (null,'Hornbeam',115,19),
                         (null,'Lime',93,16),
                         (null,'Chestnut',171,17),
                         (null,'Walnut',129,18),
                         (null,'Cherry',101,19),
                         (null,'Apple',159,20),
                         (null,'Pear',113,21),
                         (null,'Plum',91,22),
                         (null,'Apricot',167,23),
                         (null,'Peach',125,24),
                         (null,'Fig',103,25),
                         (null,'Lemon',157,26),
                         (null,'Orange',111,27),
                         (null,'Grapevine',99,28),
                         (null,'Strawberry',173,29),
                         (null,'Raspberry',131,30),
                         (null,'Blueberry',109,31),
                         (null,'Blackberry',165,32),
                         (null,'Gooseberry',123,33),
                         (null,'Currant',101,34),
                         (null,'Elderberry',128,35),
                         (null,'Crab Apple',106,36),
                         (null,'Serviceberry',155,37),
                         (null,'Mountain Ash',113,38),
                         (null,'Rowan',91,39),
                         (null,'Hawthorn',167,40),
                         (null,'Juniper',125,41),
                         (null,'Yew',103,42),
                         (null,'Holly',157,43),
                         (null,'Boxwood',111,44),
                         (null,'Privet',99,45),
                         (null,'Honeysuckle',173,46),
                         (null,'Forsythia',131,47),
                         (null,'Lilac',109,48),
                         (null,'Mock Orange',165,49),
                         (null,'Hydrangea',123,50),
                         (null,'Rose',101,51),
                         (null,'Tulip',159,52),
                         (null,'Daffodil',113,53),
                         (null,'Hyacinth',91,54),
                         (null,'Iris',167,55),
                         (null,'Lily',125,56),
                         (null,'Peony',103,57),
                         (null,'Poppy',157,58),
                         (null,'Sunflower',111,59),
                         (null,'Rose of Sharon',99,60),
                         (null,'Honeysuckle',173,61),
                         (null,'Clematis',131,62),
                         (null,'Morning Glory',109,63),
                         (null,'Wisteria',165,64),
                         (null,'Kudzu',123,65),
                         (null,'Pumpkin',101,66),
                         (null,'Squash',159,67),
                         (null,'Cucumber',113,68),
                         (null,'Tomato',91,69),
                         (null,'Pepper',167,70),
                         (null,'Eggplant',125,71),
                         (null,'Corn',103,72),
                         (null,'Beans',157,73),
                         (null,'Peas',111,74),
                         (null,'Potato',99,75),
                         (null,'Sweet Potato',173,76),
                         (null,'Yam',131,77),
                         (null,'Carrot',109,78),
                         (null,'Beet',165,79),
                         (null,'Turnip',123,80),
                         (null,'Lettuce',101,81),
                         (null,'Spinach',159,82),
                         (null,'Kale',113,83),
                         (null,'Collard Greens',91,84),
                         (null,'Mustard Greens',167,85),
                         (null,'Turnip Greens',125,86),
                         (null,'Broccoli',103,87),
                         (null,'Cauliflower',157,88),
                         (null,'Cabbage',111,89),
                         (null,'Brussels Sprouts',99,90),
                         (null,'Kohlrabi',173,91),
                         (null,'Asparagus',131,92),
                         (null,'Rhubarb',109,93),
                         (null,'Celery',165,94),
                         (null,'Artichoke',123,95),
                         (null,'Watermelon',101,96),
                         (null,'Cantaloupe',159,97),
                         (null,'Honeydew',113,98),
                         (null,'Grape',91,99),
                         (null,'Berry',167,100),
                         (null, 'Kiwi', 125, 101),
                         (null, 'Mango', 103, 102),
                         (null, 'Papaya', 157, 103),
                         (null, 'Pineapple', 111, 104),
                         (null, 'Banana', 99, 105),
                         (null, 'Coconut', 173, 106),
                         (null, 'Date', 131, 107),
                         (null, 'Fig', 109, 108),
                         (null, 'Olive', 165, 109),
                         (null, 'Almond', 123, 110),
                         (null, 'Cashew', 101, 111),
                         (null, 'Hazelnut', 159, 112),
                         (null, 'Macadamia Nut', 113, 113),
                         (null, 'Peanut', 91, 114),
                         (null, 'Pecans', 167, 115),
                         (null, 'Pistachio', 125, 116),
                         (null, 'Walnut', 103, 117),
                         (null, 'Basil', 157, 118),
                         (null, 'Bay Leaf', 111, 119),
                         (null, 'Chives', 99, 120),
                         (null, 'Cilantro', 173, 121),
                         (null, 'Cumin', 131, 122),
                         (null, 'Dill', 109, 123),
                         (null, 'Garlic', 165, 124),
                         (null, 'Ginger', 123, 125),
                         (null, 'Mint', 101, 126),
                         (null, 'Oregano', 159, 127),
                         (null, 'Parsley', 113, 128),
                         (null, 'Rosemary', 91, 129),
                         (null, 'Sage', 167, 130),
                         (null, 'Thyme', 125, 131),
                         (null, 'Turmeric', 103, 132),
                         (null, 'Vanilla', 157, 133),
                        (null, 'Oak', 132, 123),
                        (null, 'Birch', 111, 184),
                        (null, 'Pine', 50, 10),
                        (null, 'Spruce', 176, 167),
                        (null, 'Maple', 145, 193),
                        (null, 'Ash', 82, 20),
                        (null, 'Beech', 100, 152),
                        (null, 'Elm', 63, 91),
                        (null, 'Willow', 121, 11),
                        (null, 'Poplar', 196, 12),
                        (null, 'Aspen', 75, 45),
                        (null, 'Hawthorn', 154, 196),
                        (null, 'Dogwood', 138, 13),
                        (null, 'Hazelnut', 107, 18),
                        (null, 'Alder', 162, 15),
                        (null, 'Hornbeam', 115, 19),
                        (null, 'Lime', 93, 16),
                        (null, 'Chestnut', 171, 17),
                        (null, 'Walnut', 129, 18),
                        (null, 'Cherry', 101, 19),
                        (null, 'Apple', 159, 20),
                        (null, 'Pear', 113, 21),
                        (null, 'Plum', 91, 22),
                        (null, 'Apricot', 167, 23),
                        (null, 'Peach', 125, 24),
                        (null, 'Fig', 103, 25),
                        (null, 'Lemon', 157, 26),
                        (null, 'Orange', 111, 27),
                        (null, 'Grapevine', 99, 28),
                        (null, 'Strawberry', 173, 29),
                        (null, 'Raspberry', 131, 30),
                        (null, 'Blueberry', 109, 31),
                        (null, 'Blackberry', 165, 32),
                        (null, 'Gooseberry', 123, 33),
                        (null, 'Currant', 101, 34),
                        (null, 'Elderberry', 128, 35),
                        (null, 'Crab Apple', 106, 36),
                        (null, 'Serviceberry', 155, 37),
                        (null, 'Mountain Ash', 113, 38),
                        (null, 'Rowan', 91, 39),
                        (null, 'Hawthorn', 167, 40),
                        (null, 'Juniper', 125, 41),
                        (null, 'Yew', 103, 42),
                        (null, 'Holly', 157, 43),
                        (null, 'Boxwood', 111, 44),
                        (null, 'Privet', 99, 45),
                        (null, 'Honeysuckle', 173, 46),
                        (null, 'Forsythia', 131, 47),
                        (null, 'Lilac', 109, 48),
                        (null, 'Mock Orange', 165, 49),
                        (null, 'Hydrangea', 123, 50),
                        (null, 'Rose', 101, 51),
                        (null, 'Tulip', 159, 52),
                        (null, 'Daffodil', 113, 53),
                        (null, 'Hyacinth', 91, 54),
                        (null, 'Iris', 167, 55),
                        (null, 'Lily', 125, 56),
                        (null, 'Peony', 103, 57),
                        (null, 'Poppy', 157, 58),
                        (null, 'Sunflower', 111, 59),
                        (null, 'Rose of Sharon', 99, 60),
                        (null, 'Honeysuckle', 173, 61),
                        (null, 'Clematis', 131, 62),
                        (null, 'Morning Glory', 109, 63),
                        (null, 'Wisteria', 165, 64),
                        (null, 'Kudzu', 123, 65),
                        (null, 'Pumpkin', 101, 66),
                        (null, 'Squash', 159, 67),
                        (null, 'Cucumber', 113, 68),
                        (null, 'Tomato', 91, 69),
                        (null, 'Pepper', 167, 70),
                        (null, 'Eggplant', 125, 71),
                        (null, 'Corn', 103, 72),
                        (null, 'Beans', 157, 73),
                        (null, 'Peas', 111, 74),
                        (null, 'Potato', 99, 75),
                        (null, 'Sweet Potato', 173, 76),
                        (null, 'Yam', 131, 77),
                        (null, 'Carrot', 109, 78),
                        (null, 'Beet', 165, 79),
                        (null, 'Turnip', 123, 80),
                        (null, 'Lettuce', 101, 81),
                        (null, 'Spinach', 159, 82),
                        (null, 'Kale', 113, 83),
                        (null, 'Collard Greens', 91, 84),
                        (null, 'Mustard Greens', 167, 85),
                        (null, 'Turnip Greens', 125, 86),
                        (null, 'Broccoli', 103, 87),
                        (null, 'Cauliflower', 157, 88),
                        (null, 'Cabbage', 111, 89),
                        (null, 'Brussels Sprouts', 99, 90),
                        (null, 'Kohlrabi', 173, 91),
                        (null, 'Asparagus', 131, 92),
                        (null, 'Rhubarb', 109, 93),
                        (null, 'Celery', 165, 94),
                        (null, 'Artichoke', 123, 95),
                        (null, 'Watermelon', 101, 96),
                        (null, 'Cantaloupe', 159, 97),
                        (null, 'Honeydew', 113, 98),
                        (null, 'Grape', 91, 99),
                        (null, 'Berry', 167, 100),
                        (null, 'Kiwi', 125, 101),
                        (null, 'Mango', 103, 102),
                        (null, 'Papaya', 157, 103),
                        (null, 'Pineapple', 111, 104),
                        (null, 'Banana', 99, 105),
                        (null, 'Coconut', 173, 106),
                        (null, 'Date', 131, 107),
                        (null, 'Fig', 109, 108),
                        (null, 'Olive', 165, 109),
                        (null, 'Almond', 123, 110),
                        (null, 'Cashew', 101, 111),
                        (null, 'Hazelnut', 159, 112),
                        (null, 'Macadamia Nut', 113, 113),
                        (null, 'Peanut', 91, 114),
                        (null, 'Pecans', 167, 115),
                        (null, 'Pistachio', 125, 116),
                        (null, 'Walnut', 103, 117),
                        (null, 'Basil', 157, 118),
                        (null, 'Bay Leaf', 111, 119),
                        (null, 'Chives', 99, 120),
                        (null, 'Cilantro', 173, 121),
                        (null, 'Cumin', 131, 122),
                        (null, 'Dill', 109, 123),
                        (null, 'Garlic', 165, 124),
                        (null, 'Ginger', 123, 125),
                        (null, 'Mint', 101, 126),
                        (null, 'Oregano', 159, 127),
                        (null, 'Parsley', 113, 128),
                        (null, 'Rosemary', 91, 129),
                        (null, 'Sage', 167, 130),
                        (null, 'Thyme', 125, 131),
                        (null, 'Turmeric', 103, 132),
                        (null, 'Vanilla', 157, 133);
            """);

        } catch (SQLException e){
            throw new MigrationException(e);
        }
    }
}
